# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11hAJTxY8xHaysxq6eVfrJshEJmiVdHZ3
"""

!pip install dask

import dask.dataframe as dd
import dask.array as da
from dask.delayed import delayed
from dask.distributed import Client
import dask.dataframe as dd
import pandas as pd
import time

client = Client()
client

pdf = pd.read_excel("/content/college_comparing_matrix.xlsx", sheet_name="Вступ", engine="openpyxl")

ddf = dd.from_pandas(pdf, npartitions=1)

print(ddf.head())
print(ddf.info())

num_rows = len(ddf)
print(f"Кількість записів у датасеті: {num_rows}")

num_specialties = ddf['Спеціальність'].nunique().compute()
print(f"Кількість спеціальностей, на яких відбувався вступ: {num_specialties}")

stats = ddf['Вступ'].describe().compute()
print(f"Статистика: {stats}")

grouped_specialties = ddf.groupby('Спеціальність')['Вступ'].sum().compute()
print(f"Групування та підрахунок вступників по спеціальностям: {grouped_specialties}")

@delayed
def compute_mean(ddf, column):
    return ddf.groupby('Спеціальність')[column].mean()

mean_value = compute_mean(ddf, 'Вступ')
print("Середнє значення вступників для кожної спеціальності:")
print(mean_value.compute())

result = ddf.groupby('Спеціальність')['Вступ'].sum().compute()
print(f"Популярні спеціальності за кількістю вступників: {result}")

client = Client()
print(client)

result = ddf.groupby('Спеціальність')['Вступ'].sum().compute()

print(result)